version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.6.1
    env_file:
      - es.env
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.6.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

  fluentd:
    build: ./custom-fluentd
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
